services:
  - type: web
    name: mee
    runtime: static
    staticPublishPath: GameDataFiles
    autoDeployTrigger: commit


    routes:
      - type: rewrite
        source: /*
        destination: /index.html
